# Generated by Django 4.2.13 on 2024-07-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_description_remove_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Facebook',
            new_name='PAGIBIG_No',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Instagram',
            new_name='PhilHealth_No',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Tiktok',
            new_name='SSS_No',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Twitter',
            new_name='Tin_No',
        ),
    ]
