# Generated by Django 4.2.13 on 2024-07-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_facebook_item_pagibig_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='PAGIBIG_No',
        ),
        migrations.RemoveField(
            model_name='item',
            name='PhilHealth_No',
        ),
        migrations.RemoveField(
            model_name='item',
            name='SSS_No',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Tin_No',
        ),
    ]
